services:
 - docker
install:
  - docker build -t unifi .
  - docker run -d -p 8443:8443 -p 8080:8080 -e RUNAS_UID0=true --name unifi unifi
script:
  - docker ps | grep -q unifi
  - docker logs unifi
  - sleep 10 && curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 60 -kILs --fail http://127.0.0.1:8080 || exit 1
